version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/nodejs-server-v2
hooks:
  BeforeInstall:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
  ValidateService:
